[project]
name = 'OpenSphere'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.content]
path = 'contracts/content.clar'
clarity_version = 2
epoch = 2.5

[contracts.social-token]
path = 'contracts/social-token.clar'
clarity_version = 2
epoch = 2.5

[contracts.user-profile]
path = 'contracts/user-profile.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
